platform: &platform "amax"
exp_task: &exp_task "zero_scroll"
state: &state "test"
id: &id "vanilla_mamba-2.8b"

defaults:
  - _self_
  - platform: amax
  - task: zero_scroll

hydra:
  job:
    name: hydra_${exp_task}
  run:
    dir: ./runs/${exp_task}/${id}

experiment:
  seed: 27
  results_save_dir: ${exp_path}/${exp_task}/${id}/results
  device_num: 1
  node_num: 1