exp_task: &exp_task "passkey_search"
state: &state "test"
job_id: &job_id N4096_D256-N4096_D32
model_name: &model_name "mamba-1_4b"

defaults:
  - _self_
  - platform: "amax_a100"
  - task: *exp_task
  - model: *model_name  # use_relative_position | use_abs_position | load_model_state_dict

hydra:
  job:
    name: hydra_${exp_task}
  run:
    dir: ./runs/${exp_task}/${model}

experiment:
  seed: 27
  results_save_dir: ${exp_task}/${model_name}/version_${job_id}/results
  device_num: 4
  node_num: 1