SAVE_DIR: &SAVE_DIR "/nvme/zecheng/ckpt"
JOB_ID: &JOB_ID 2
TASK: &TASK "text_infilling"

hydra:
  job:
    id: ${JOB_ID}
    name: hydra_${TASK}
  run:
    dir: ${SAVE_DIR}/${TASK}/version_${JOB_ID}/${hydra.job.name} 

dataset:
  test_data_path: "/nvme/zecheng/data/roc_stories/processed_2017/test.jsonl"
  max_seq_length: 512
  train_batch_size: 16
  val_batch_size: 16
  nworkers: 12
  pin_memory: False
  inference_mode: True
  cluster_batch: False

model:
  model_name_or_path: "/nvme/hf_models/mamba-1.4b"
  ckpt_path: "/nvme/zecheng/ckpt/text_infilling/version_1/checkpoints/last.ckpt"
  
tokenizer:
  tokenizer_name_or_path: "/nvme/hf_models/gpt-neo-1.3B"

experiment:
  seed: 27
  model_save_dir: ${SAVE_DIR}
  task: ${TASK}
  version: ${JOB_ID}
  device_num: 1
  node_num: 1