platform: &platform "amax"
JOB_ID: &JOB_ID 1
state: &state "test"
exp_task: &exp_task "passkey_search"
model_name: &model_name "mamba-1_4b"

hydra:
  job:
    name: hydra_${exp_task}
  run:
    dir: ./runs/${exp_task}-${model_name}/${state}/${hydra.job.name}

experiment:
  seed: 27
  max_seq_length: 160
  model_save_dir: ${exp_task}-${model_name}/version_${JOB_ID}
  results_save_dir: ${exp_task}-${model_name}/version_${JOB_ID}/results
  device_num: 1
  node_num: 1