SAVE_DIR: &SAVE_DIR "/nvme/zecheng/ckpt"
JOB_ID: &JOB_ID 5
TASK: &TASK "text_infilling"

hydra:
  job:
    id: ${JOB_ID}
    name: hydra_${TASK}
  run:
    dir: ${SAVE_DIR}/${TASK}/version_${JOB_ID}/${hydra.job.name} 

dataset:
  file_path: "/nvme/zecheng/data/roc_stories/processed_2017/train.jsonl"
  max_seq_length: 512
  train_batch_size: 18
  val_batch_size: 18
  nworkers: 12
  pin_memory: False
  inference_mode: False
  cluster_batch: False

model:
  model_name_or_path: "/nvme/hf_models/mamba-1.4b"
  
tokenizer:
  tokenizer_name_or_path: "/nvme/hf_models/EleutherAI/gpt-neox-20b"

optimizer:
  optimizer_type: "adamw"
  lr: 5e-5

lr_scheduler:
  scheduler_type: "get_cosine_schedule_with_warmup"
  warmup_steps: 0

experiment:
  seed: 27
  model_save_dir: ${SAVE_DIR}
  task: ${TASK}
  version: ${JOB_ID}
  num_training_steps: 20000
  device_num: 6
  node_num: 1