SAVE_DIR: &SAVE_DIR "/nvme/zecheng/ckpt"
JOB_ID: &JOB_ID 1
TASK: &TASK "text_infilling_gpt"

hydra:
  job:
    id: ${JOB_ID}
    name: hydra_${TASK}
  run:
    dir: ${SAVE_DIR}/${TASK}/version_${JOB_ID}/${hydra.job.name} 

dataset:
  file_path: "/nvme/zecheng/data/roc_stories/processed_2017/train.jsonl"
  max_seq_length: 512
  train_batch_size: 6
  val_batch_size: 6
  nworkers: 12
  pin_memory: False
  inference_mode: False
  cluster_batch: False

model:
  model_name_or_path: "/nvme/hf_models/gpt-neo-1.3B"
  
tokenizer:
  tokenizer_name_or_path: "/nvme/hf_models/gpt-neo-1.3B"

device:
  accelerator: "cuda"
  device_num: 7
  precision: "bf16"

experiment:
  seed: 27
  model_save_dir: ${SAVE_DIR}
  task: ${TASK}
  version: ${JOB_ID}
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 0.1
  eps: 0.001
  num_training_steps: 10000
  warmup_steps: 1000
  lr: 5e-5
