platform: &platform "amax"
JOB_ID: &JOB_ID 1
state: &state "train"
model: &model "vanilla_mamba-2.8b"

defaults:
  - _self_
  - platform: amax
  - task: simplepajama
  - model: mamba-2_8b

hydra:
  job:
    name: hydra_${exp_task}
  run:
    dir: ./runs/${exp_task}/${model}


optimizer:
  optimizer_type: "adamw"
  lr: 5e-5

lr_scheduler:
  scheduler_type: "get_cosine_schedule_with_warmup"
  warmup_steps: 0


experiment:
  seed: 27
  model_save_dir: ${SAVE_DIR}
  task: ${TASK}
  version: ${JOB_ID}
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 0.1
  eps: 0.001
  num_training_steps: 10000
  warmup_steps: 1000
  peak_lr: 0.0002
  last_lr: 0.00001
  device_num: 1
  node_num: 1