SAVE_DIR: &SAVE_DIR "/nvme/zecheng/ckpt"
JOB_ID: &JOB_ID 1
TASK: &TASK "vanilla_mamba"
TEST_TASK: &TEST_TASK "zero_scroll"

hydra:
  job:
    id: ${JOB_ID}
    name: hydra_${TASK}
  run:
    dir: ${SAVE_DIR}/${TASK}/${TEST_TASK}/${hydra.job.name} 

dataset:
  data_path: "/nvme/zecheng/data/ZeroSCROLLS"
  processed_data_path: "/nvme/zecheng/data/ZeroSCROLLS/all_testing_data.pkl"
  ctx_len: 10000
  subsets: ['gov_report', 'summ_screen_fd', 'qmsum', 'qasper', 'narrative_qa', 'quality', 'musique', 'squality', 'space_digest','book_sum_sort']
  nworkers: 12
  pin_memory: False
  inference_mode: True
  cluster_batch: False

model:
  model_name_or_path: "/nvme/hf_models/mamba-1.4b"
  ckpt_path: "/nvme/hf_models/mamba-1.4b/pytorch_model.bin"
  load_model_state_dict: True
  use_position: False
  # ckpt_path: "/nvme/zecheng/ckpt/mamba-chat/checkpoint-1000/pytorch_model.bin"

tokenizer:
  tokenizer_name_or_path: "/nvme/hf_models/EleutherAI/gpt-neox-20b"

experiment:
  seed: 27
  max_seq_length: 512
  model_save_dir: ${SAVE_DIR}
  results_save_dir: ${SAVE_DIR}/${TASK}/${TEST_TASK}
  test_task: ${TEST_TASK}
  version: ${JOB_ID}
  device_num: 1
  node_num: 1
