python peft_model.py \
    --cf config/llama7b.yaml \
    --output_dir /zecheng/detox-cot/llama2 \
    --save_strategy "epoch" \
    --num_train_epochs 15 \
    --remove_unused_columns False \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --logging_steps 1 \
    --dataloader_num_workers 0 \
    --lr_scheduler_type "cosine" \
    --report_to "tensorboard" \
    --gradient_checkpointing True \
    --fp16 True;