dataset:
  data_path: ""
  module: 'custom_dataset.AR_ywj' # Custom dataset module path
  class_name: 'MQARDataset'  # dataset class name
  nworkers: 12
  inference_mode: True
  cluster_batch: False
  vocab_size: 8192
  num_examples: 3000
  input_seq_len: 64
  num_kv_pairs: 4
  test_power_a: 0.01

other_cfgs: 
  max_generation_length: 48
  testing_max_ctx: 32000


  