model_name_or_path: "mamba-370m-hf"
tokenizer_name_or_path: "mamba-370m-hf"
ckpt_path: "/public/home/ljt/tzc/ckpt/pretrain/slimpajama/mamba_370m_big_kernel-k16/model.bin"
use_custom_module: True
load_model_state_dict: True
use_relative_position: False
use_abs_position: False
max_position_embeddings: 16384
custom_conv1d: True
conv1d_configs:
  kernel_sizes: 16

