python train_vqllama.py \
    --model_name_or_path "/zecheng2/model_hub/Llama-2-7b-hf" \
    --tokenier_config_path "/zecheng2/model_hub/Llama-2-7b-hf" \
    --data_path "/zecheng2/svg/icon-shop/pkl_data/efficient_inference_full_data/test_vqllama_quantizer/version_8/epoch_84/inference_full_data_compress_1_snaps_merged.pkl" \
    --output_dir "/zecheng2/vqllama/vqllama_llama/version_1" \
    --model_max_length 1500 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "epoch" \
    --dataloader_num_workers 64 \
    --fp16 True \
    --remove_unused_columns False \
    --vqvae_config_path "configs/deepspeed/vqvae_config.yaml";